### ISSUE TITLE
Not able merge job description 

### ISSUE THREAD

**Issue by ankitbajpai1607** [Shubhamsharma585/Shine-masai#17]
library is present in job description 

Failed to compile
./node_modules/react-text-collapse/dist/ReactTextCollapse.js
Module not found: Can't resolve 'react-motion' in 'C:\Users\ankit\React\Project\Shine-masai\shine\node_modules\react-text-collapse\dist'error:--

**Comment by Vinesh3124** [comment]
Fixed the issues installed React motion library
